<?php
/**
 * @file
 * Allows setting a site to use a remote set of files for the files directory.
 * 
 * @author Nicholas Alipaz - http://nicholas.alipaz.net/ (email through contact form)
 */

/**
 * Implementation of hook_form_alter()
 */
function hosting_remote_files_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    $form['remote_files'] = array(
      '#type' => 'fieldset',
      '#title' => t('Remote Files'),
      '#description' => t('Allows setting a site to use a remote set of files for the files directory..'),
    );
    $form['remote_files']['remote_files_status'] = array(
      '#type' => 'checkbox',
      '#title' => t('Remote Files'),
      '#default_value' => $form['#node']->remote_files_status ? $form['#node']->remote_files_status : '',
      '#weight' => 0,
    );
    $form['remote_files']['remote_files_uri'] = array(
      '#type' => 'textfield',
      '#title' => t('URI'),
      '#default_value' => $form['#node']->remote_files_uri ? $form['#node']->remote_files_uri : '',
      '#weight' => 0,
    );

    return $form;
  }
}

/**
 * Implementation of hook_insert()
 */
function hosting_remote_files_insert($node) {
  if (!empty($node->remote_files_status)) {
    db_query("INSERT INTO {hosting_remote_files} (vid, nid, status, uri) VALUES (%d, %d, %d, '%s')", $node->vid, $node->nid, $node->remote_files_status, $node->remote_files_uri);
  }
}

/**
 * Implementation of hook_update()
 */
function hosting_remote_files_update($node) {
  if (FALSE === db_fetch_array(db_query("SELECT status AS remote_files_status, uri AS remote_files_uri FROM {hosting_remote_files} WHERE vid = %d", $node->vid))) {
    hosting_remote_files_insert($node);
  }
  else {
    db_query("UPDATE {hosting_remote_files} SET status = %d, uri = '%s' WHERE vid = %d", $node->remote_files_status, $node->remote_files_uri, $node->vid);
  }

}

/**
 * Implementation of hook_delete()
 */
function hosting_remote_files_delete($node) {
  db_query("DELETE FROM {hosting_remote_files} WHERE nid=%d", $node->nid);
}

/**
 * Implementation of hook_delete_revision()
 */
function hosting_remote_files_delete_revision($node) {
  db_query("DELETE FROM {hosting_remote_files} WHERE vid=%d", $node->vid);
}

/**
 * Implementation of hook_nodeapi()
 */
function hosting_remote_files_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'site') {
    switch ($op) {
    case 'insert':
        hosting_remote_files_insert($node);
        break;
      case 'update':
        hosting_remote_files_update($node);
        break;
      case 'delete' :
        hosting_remote_files_delete($node);
        break;
      case 'delete revision':
        hosting_remote_files_delete_revision($node);
        break;
      case 'load':
        $additions = db_fetch_array(db_query("SELECT status AS remote_files_status, uri AS remote_files_uri FROM {hosting_remote_files} WHERE vid = %d", $node->vid));
        return $additions;
        break;
    }
  }
}
